# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/apps/api-router"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/apps/api-worker"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/admin"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/agent"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/ai-maint"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/assets"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/db"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/image-tools"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/libs"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/sentry"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/theme"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/packages/workers"
    schedule:
      interval: weekly
