name = "goldshore-web"
pages_build_output_dir = "dist"
compatibility_date = "2025-10-05"

[vars]
CF_TEAM_DOMAIN = "goldshore"
VITE_APP_ENV = "dev"
VITE_PUBLIC_API = "http://localhost:8787" # Default for local dev
VITE_PUBLIC_GATEWAY = "http://localhost:8788" # Default for local dev

# ======================================================================================
# PRODUCTION ENVIRONMENT
# ======================================================================================
[env.production]
[env.production.vars]
VITE_APP_ENV = "production"
VITE_PUBLIC_API = "https://api.goldshore.org"
VITE_PUBLIC_GATEWAY = "https://gateway.goldshore.org"

# ======================================================================================
# PREVIEW ENVIRONMENT
# ======================================================================================
[env.preview]
[env.preview.vars]
VITE_APP_ENV = "preview"
VITE_PUBLIC_API = "https://api-preview.goldshore.org"
VITE_PUBLIC_GATEWAY = "https://gateway-preview.goldshore.org"
